//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mdl_language.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mdl_language.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiungi.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avviso.
        /// </summary>
        internal static string AdviceLabel {
            get {
                return ResourceManager.GetString("AdviceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Importo.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salvare le modifiche?.
        /// </summary>
        internal static string askSaveChanges {
            get {
                return ResourceManager.GetString("askSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gli allegati sono troppo grandi, non saranno modificati. Esco comunque?.
        /// </summary>
        internal static string attachmentTooBig {
            get {
                return ResourceManager.GetString("attachmentTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esportazione errata.
        /// </summary>
        internal static string badExport {
            get {
                return ResourceManager.GetString("badExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Grassetto.
        /// </summary>
        internal static string bold {
            get {
                return ResourceManager.GetString("bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A causa di un bug di Office, documentato qui: http://support.microsoft.com/kb/320369 è necessario installare Microsoft Office XP Multilingual User Interface Pack..
        /// </summary>
        internal static string bugOfficeXp {
            get {
                return ResourceManager.GetString("bugOfficeXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La chiusura del form è temporaneamente inibita, attendere..
        /// </summary>
        internal static string cantCloseWait {
            get {
                return ResourceManager.GetString("cantCloseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile eliminare l&apos;oggetto..
        /// </summary>
        internal static string cantDeleteObject {
            get {
                return ResourceManager.GetString("cantDeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per chiudere una maschera è necessario prima chiudere le maschere da essa dipendenti..
        /// </summary>
        internal static string childFormStillOpened {
            get {
                return ResourceManager.GetString("childFormStillOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il comando {cmd} ha invalidato la transazione.
        /// </summary>
        internal static string cmdInvalidatedTransaction {
            get {
                return ResourceManager.GetString("cmdInvalidatedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; necessario selezionare una colonna.
        /// </summary>
        internal static string colRequired {
            get {
                return ResourceManager.GetString("colRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome colonna.
        /// </summary>
        internal static string columnName {
            get {
                return ResourceManager.GetString("columnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La condizione di ricerca impostata era: &apos;{filter}&apos;..
        /// </summary>
        internal static string conditionSetWas {
            get {
                return ResourceManager.GetString("conditionSetWas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei sicuro di voler eliminare l&apos;elenco {listType}.
        /// </summary>
        internal static string confirmDeleteListType {
            get {
                return ResourceManager.GetString("confirmDeleteListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei sicuro di voler cancellare?.
        /// </summary>
        internal static string confirmDeleting {
            get {
                return ResourceManager.GetString("confirmDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conferma.
        /// </summary>
        internal static string confirmTitle {
            get {
                return ResourceManager.GetString("confirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non sono riuscito a collegare la riga alla tabella {tableName} nel metadato {name}.
        /// </summary>
        internal static string couldNotLinkTable {
            get {
                return ResourceManager.GetString("couldNotLinkTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La voce selezionata non poteva essere scelta..
        /// </summary>
        internal static string couldNotSelectRow {
            get {
                return ResourceManager.GetString("couldNotSelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creato il {data}.
        /// </summary>
        internal static string createdAt {
            get {
                return ResourceManager.GetString("createdAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creato da {user}.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creazione/Ultima Modifica.
        /// </summary>
        internal static string CreateLastMod {
            get {
                return ResourceManager.GetString("CreateLastMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea ticket.
        /// </summary>
        internal static string CreateTicketLabel {
            get {
                return ResourceManager.GetString("CreateTicketLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dizionario dati.
        /// </summary>
        internal static string DataDictionary {
            get {
                return ResourceManager.GetString("DataDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Foglio Dati.
        /// </summary>
        internal static string dataFolder {
            get {
                return ResourceManager.GetString("dataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La connessione al db è stata interrotta. E&apos; necessario disconnettersi, ripristinare la rete e riconnettersi al db..
        /// </summary>
        internal static string dbConnectionInterrupted {
            get {
                return ResourceManager.GetString("dbConnectionInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome campo su DB.
        /// </summary>
        internal static string dbFieldName {
            get {
                return ResourceManager.GetString("dbFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tabella sul db.
        /// </summary>
        internal static string dbTableName {
            get {
                return ResourceManager.GetString("dbTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina/Annulla.
        /// </summary>
        internal static string DeleteCancelLabel {
            get {
                return ResourceManager.GetString("DeleteCancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancello l&apos;oggetto {name} dalla tabella {tableName}.
        /// </summary>
        internal static string deleteFromTable {
            get {
                return ResourceManager.GetString("deleteFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancella.
        /// </summary>
        internal static string DeleteLable {
            get {
                return ResourceManager.GetString("DeleteLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancello la riga selezionata dalla tabella {name}({tableName}).
        /// </summary>
        internal static string deleteSelectedRowFromTable {
            get {
                return ResourceManager.GetString("deleteSelectedRowFromTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a descrizione.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Effettua Ricerca.
        /// </summary>
        internal static string DoSearchLabel {
            get {
                return ResourceManager.GetString("DoSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DO_SYSCMD: Error running {cmd} Result got: {res}.
        /// </summary>
        internal static string doSysCmdError {
            get {
                return ResourceManager.GetString("doSysCmdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Correggi.
        /// </summary>
        internal static string EditLable {
            get {
                return ResourceManager.GetString("EditLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esportazione vuota.
        /// </summary>
        internal static string emptyExport {
            get {
                return ResourceManager.GetString("emptyExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (vuoto).
        /// </summary>
        internal static string EmptyWithinPar {
            get {
                return ResourceManager.GetString("EmptyWithinPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore aprendo la connessione nel salvataggio.
        /// </summary>
        internal static string errOpeningDuringSave {
            get {
                return ResourceManager.GetString("errOpeningDuringSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile eliminare l&apos;elenco  {listType}.
        /// </summary>
        internal static string errorDeletingListType {
            get {
                return ResourceManager.GetString("errorDeletingListType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un determinato campo non può essere vuoto..
        /// </summary>
        internal static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un campo chiave non può essere vuoto o duplicato..
        /// </summary>
        internal static string ErrorEmptyKey {
            get {
                return ResourceManager.GetString("ErrorEmptyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;esportazione in Excel. Riprovare e se l&apos;errore persiste contattare l&apos;assistenza..
        /// </summary>
        internal static string errorExportingExcel {
            get {
                return ResourceManager.GetString("errorExportingExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nel caricamento del metadato {unaliased}. E&apos; necessario riavviare il programma..
        /// </summary>
        internal static string errorLoadingMeta {
            get {
                return ResourceManager.GetString("errorLoadingMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore aprendo la connessione.
        /// </summary>
        internal static string errorOpeningConnection {
            get {
                return ResourceManager.GetString("errorOpeningConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nell&apos;esecuzione del comando {command}.
        /// </summary>
        internal static string errorRunningCommand {
            get {
                return ResourceManager.GetString("errorRunningCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore eseguendo il comando {cmd}
        ///E&apos; necessario chiudere la maschera..
        /// </summary>
        internal static string errorRunningCommandCloseWindow {
            get {
                return ResourceManager.GetString("errorRunningCommandCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella selezione della riga.
        /// </summary>
        internal static string errorSelectingRow {
            get {
                return ResourceManager.GetString("errorSelectingRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella visualizzazione del form.
        /// </summary>
        internal static string errorShowingForm {
            get {
                return ResourceManager.GetString("errorShowingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo carattere.
        /// </summary>
        internal static string fontName {
            get {
                return ResourceManager.GetString("fontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dimensione carattere.
        /// </summary>
        internal static string fontSize {
            get {
                return ResourceManager.GetString("fontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile eliminare le condizioni.
        /// </summary>
        internal static string impossibleToDeleteConditions {
            get {
                return ResourceManager.GetString("impossibleToDeleteConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile salvare la condizione.
        /// </summary>
        internal static string impossibleToSaveCondition {
            get {
                return ResourceManager.GetString("impossibleToSaveCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni sull&apos;oggetto.
        /// </summary>
        internal static string InfoAboutObject {
            get {
                return ResourceManager.GetString("InfoAboutObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annullo l&apos;inserimento dell&apos;oggetto {name} nella tabella {tableName}.
        /// </summary>
        internal static string insertCancelOnTable {
            get {
                return ResourceManager.GetString("insertCancelOnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; stato premuto il tasto inserisci copia. Si desidera davvero creare una copia dei dati già salvati?.
        /// </summary>
        internal static string InsertCopyConfirm {
            get {
                return ResourceManager.GetString("InsertCopyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci copia.
        /// </summary>
        internal static string InsertCopyLabel {
            get {
                return ResourceManager.GetString("InsertCopyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci.
        /// </summary>
        internal static string InsertLabel {
            get {
                return ResourceManager.GetString("InsertLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La tabella {tableName} contiene dati non validi. Contattare il servizio di assistenza..
        /// </summary>
        internal static string invalidDataOnTable {
            get {
                return ResourceManager.GetString("invalidDataOnTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data non valida.
        /// </summary>
        internal static string invalidDate {
            get {
                return ResourceManager.GetString("invalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Corsivo.
        /// </summary>
        internal static string italic {
            get {
                return ResourceManager.GetString("italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco.
        /// </summary>
        internal static string list {
            get {
                return ResourceManager.GetString("list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posizione colonna.
        /// </summary>
        internal static string listColPos {
            get {
                return ResourceManager.GetString("listColPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome Elenco: &apos;{listingType}&apos;..
        /// </summary>
        internal static string listNameIs {
            get {
                return ResourceManager.GetString("listNameIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco {name}.
        /// </summary>
        internal static string ListOfName {
            get {
                return ResourceManager.GetString("ListOfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modificato il {data}.
        /// </summary>
        internal static string modifiedAt {
            get {
                return ResourceManager.GetString("modifiedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modificato da {user}.
        /// </summary>
        internal static string modifiedBy {
            get {
                return ResourceManager.GetString("modifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore: C&apos;è più di una riga nella tabella {table}.
        /// </summary>
        internal static string moreThanOneRowInTable {
            get {
                return ResourceManager.GetString("moreThanOneRowInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna condizione è stata usata..
        /// </summary>
        internal static string noConditionUsed {
            get {
                return ResourceManager.GetString("noConditionUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun elemento trovato..
        /// </summary>
        internal static string NoElementFound {
            get {
                return ResourceManager.GetString("NoElementFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun oggetto trovato.
        /// </summary>
        internal static string noObjectFound {
            get {
                return ResourceManager.GetString("noObjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna riga trovata..
        /// </summary>
        internal static string NoRowFound {
            get {
                return ResourceManager.GetString("NoRowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nella tabella &apos;{table}&apos; non è stata trovata alcuna riga..
        /// </summary>
        internal static string noRowFoundInTable {
            get {
                return ResourceManager.GetString("noRowFoundInTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Appunti.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La transazione corrente non è più valida.
        /// </summary>
        internal static string noValidTransaction {
            get {
                return ResourceManager.GetString("noValidTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Apri documento collegato.
        /// </summary>
        internal static string OpenRelatedDocument {
            get {
                return ResourceManager.GetString("OpenRelatedDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; necessario selezionare un operatore.
        /// </summary>
        internal static string operatorRequired {
            get {
                return ResourceManager.GetString("operatorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Totale Complessivo.
        /// </summary>
        internal static string overallTotal {
            get {
                return ResourceManager.GetString("overallTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; stata inserita una riga con la stessa chiave primaria di un altra esistente.  E&apos; necessario modificare i dati immessi per salvarli..
        /// </summary>
        internal static string primaryKeyConflict {
            get {
                return ResourceManager.GetString("primaryKeyConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a readObjectArray: Error running {query}.
        /// </summary>
        internal static string readObjArrayError {
            get {
                return ResourceManager.GetString("readObjArrayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiorna.
        /// </summary>
        internal static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a risultato.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riga richiesta non trovata.
        /// </summary>
        internal static string rowNotFound {
            get {
                return ResourceManager.GetString("rowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salvataggio.
        /// </summary>
        internal static string saving {
            get {
                return ResourceManager.GetString("saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a (Ricerca).
        /// </summary>
        internal static string SearchWithinPar {
            get {
                return ResourceManager.GetString("SearchWithinPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La riga selezionata non è più presente nel db..
        /// </summary>
        internal static string selectedRowNotPresent {
            get {
                return ResourceManager.GetString("selectedRowNotPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona il file da creare.
        /// </summary>
        internal static string selectFile {
            get {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona.
        /// </summary>
        internal static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imposta Ricerca.
        /// </summary>
        internal static string SetSearchLabel {
            get {
                return ResourceManager.GetString("SetSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attendere l&apos;apertura del form per chiuderlo!.
        /// </summary>
        internal static string stillNotOpenedForm {
            get {
                return ResourceManager.GetString("stillNotOpenedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Campo troppo lungo.
        /// </summary>
        internal static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tabella:{searchTable}
        ///Filtro applicato:{checkfilter}.
        /// </summary>
        internal static string TableFilterApplied {
            get {
                return ResourceManager.GetString("TableFilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tabella:{middle} presente in memoria..
        /// </summary>
        internal static string TableMiddleInMemory {
            get {
                return ResourceManager.GetString("TableMiddleInMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Titolo.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Totale.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sottolineato.
        /// </summary>
        internal static string underline {
            get {
                return ResourceManager.GetString("underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ci sono modifiche ai dati non salvate. Si desidera perdere le modifiche?.
        /// </summary>
        internal static string unsavedDataWarn {
            get {
                return ResourceManager.GetString("unsavedDataWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; necessario inserire un valore.
        /// </summary>
        internal static string valueRequired {
            get {
                return ResourceManager.GetString("valueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visibile.
        /// </summary>
        internal static string visible {
            get {
                return ResourceManager.GetString("visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attendere la fine dell&apos;esecuzione del comando.
        /// </summary>
        internal static string waitForCommandCompletion {
            get {
                return ResourceManager.GetString("waitForCommandCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attendere il completamento dell&apos;operazione per chiudere il form..
        /// </summary>
        internal static string waitForOperationEnd {
            get {
                return ResourceManager.GetString("waitForOperationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione.
        /// </summary>
        internal static string WarningLabel {
            get {
                return ResourceManager.GetString("WarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Larghezza.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per poter procedere è necessario CHIUDERE la finestra con cui si stava lavorando e ripetere l&apos;operazione.
        ///E&apos; consigliabile ad ogni modo chiamare il servizio assistenza lasciando aperta questa schermata..
        /// </summary>
        internal static string windowMustBeClosed {
            get {
                return ResourceManager.GetString("windowMustBeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dati errati.
        /// </summary>
        internal static string wrongData {
            get {
                return ResourceManager.GetString("wrongData", resourceCulture);
            }
        }
    }
}
